name: my work flow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout action
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "welcome to the first code"

        - name: List file 
          run: ls  
        - name: readfile
          run: cat README.MD  